{{- if or .Values.clerk.publishableKey .Values.clerk.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: byteorder-clerk
type: Opaque
stringData:
  publishable-key: {{ .Values.clerk.publishableKey | quote }}
  secret-key: {{ .Values.clerk.secretKey | quote }}
{{- end }}
